### ISSUE TITLE
Testing and timing algorith

### ISSUE THREAD

**Issue by JuanFMontesinos** [seungwonpark/istft-pytorch#3]
Hi, 
Some results
MSE [deconv: 0.00000 / irff: 0.00000 ]@ filter_length = 2, hop_length = 1, time_deconv = 4.002,time_irff = 7996.547
MSE [deconv: 0.00368 / irff: 0.00368 ]@ filter_length = 2, hop_length = 2, time_deconv = 1.367,time_irff = 3964.140
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 4, hop_length = 1, time_deconv = 1.002,time_irff = 7918.723
MSE [deconv: 0.00046 / irff: 0.00046 ]@ filter_length = 4, hop_length = 2, time_deconv = 0.997,time_irff = 3950.203
MSE [deconv: 0.00230 / irff: 0.00230 ]@ filter_length = 4, hop_length = 4, time_deconv = 1.000,time_irff = 1965.112
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 8, hop_length = 1, time_deconv = 1.575,time_irff = 7075.405
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 8, hop_length = 2, time_deconv = 1.009,time_irff = 3523.832
MSE [deconv: 0.00035 / irff: 0.00035 ]@ filter_length = 8, hop_length = 4, time_deconv = 1.017,time_irff = 1756.467
MSE [deconv: 0.00219 / irff: 0.00219 ]@ filter_length = 8, hop_length = 8, time_deconv = 1.014,time_irff = 879.968
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 16, hop_length = 1, time_deconv = 1.840,time_irff = 7027.438
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 16, hop_length = 2, time_deconv = 1.065,time_irff = 3500.918
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 16, hop_length = 4, time_deconv = 0.991,time_irff = 1747.602
MSE [deconv: 0.00035 / irff: 0.00035 ]@ filter_length = 16, hop_length = 8, time_deconv = 0.985,time_irff = 877.819
MSE [deconv: 0.00219 / irff: 0.00219 ]@ filter_length = 16, hop_length = 16, time_deconv = 0.994,time_irff = 441.234
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 32, hop_length = 1, time_deconv = 2.610,time_irff = 7034.293
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 32, hop_length = 2, time_deconv = 1.293,time_irff = 3516.427
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 32, hop_length = 4, time_deconv = 1.024,time_irff = 1751.083
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 32, hop_length = 8, time_deconv = 0.968,time_irff = 881.138
MSE [deconv: 0.00035 / irff: 0.00035 ]@ filter_length = 32, hop_length = 16, time_deconv = 0.999,time_irff = 438.753
MSE [deconv: 0.00218 / irff: 0.00218 ]@ filter_length = 32, hop_length = 32, time_deconv = 0.967,time_irff = 219.733
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 64, hop_length = 1, time_deconv = 4.011,time_irff = 7013.569
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 64, hop_length = 2, time_deconv = 2.048,time_irff = 3500.263
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 64, hop_length = 4, time_deconv = 1.220,time_irff = 1765.662
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 64, hop_length = 8, time_deconv = 1.014,time_irff = 889.009
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 64, hop_length = 16, time_deconv = 1.006,time_irff = 444.584
MSE [deconv: 0.00034 / irff: 0.00034 ]@ filter_length = 64, hop_length = 32, time_deconv = 1.019,time_irff = 225.643
MSE [deconv: 0.00220 / irff: 0.00220 ]@ filter_length = 64, hop_length = 64, time_deconv = 1.001,time_irff = 109.583
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 128, hop_length = 1, time_deconv = 8.886,time_irff = 7168.705
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 128, hop_length = 2, time_deconv = 4.435,time_irff = 3600.540
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 128, hop_length = 4, time_deconv = 1.807,time_irff = 1849.381
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 128, hop_length = 8, time_deconv = 1.250,time_irff = 903.769
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 128, hop_length = 16, time_deconv = 1.026,time_irff = 456.363
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 128, hop_length = 32, time_deconv = 1.170,time_irff = 229.442
MSE [deconv: 0.00035 / irff: 0.00035 ]@ filter_length = 128, hop_length = 64, time_deconv = 1.014,time_irff = 114.862
MSE [deconv: 0.00217 / irff: 0.00217 ]@ filter_length = 128, hop_length = 128, time_deconv = 1.029,time_irff = 61.646
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 256, hop_length = 1, time_deconv = 25.326,time_irff = 7266.758
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 256, hop_length = 2, time_deconv = 12.293,time_irff = 3597.168
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 256, hop_length = 4, time_deconv = 3.807,time_irff = 1779.808
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 256, hop_length = 8, time_deconv = 1.782,time_irff = 891.179
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 256, hop_length = 16, time_deconv = 1.214,time_irff = 445.969
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 256, hop_length = 32, time_deconv = 1.008,time_irff = 224.918
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 256, hop_length = 64, time_deconv = 0.969,time_irff = 112.708
MSE [deconv: 0.00034 / irff: 0.00034 ]@ filter_length = 256, hop_length = 128, time_deconv = 0.943,time_irff = 55.521
Failed @ filter_length = 256, hop_length = 256, a:torch.Size([88200]), o torch.Size([129, 345, 2])
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 512, hop_length = 1, time_deconv = 53.202,time_irff = 7131.690
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 512, hop_length = 2, time_deconv = 24.741,time_irff = 3564.239
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 512, hop_length = 4, time_deconv = 8.556,time_irff = 1788.651
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 512, hop_length = 8, time_deconv = 3.751,time_irff = 887.797
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 512, hop_length = 16, time_deconv = 1.882,time_irff = 445.455
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 512, hop_length = 32, time_deconv = 1.339,time_irff = 222.931
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 512, hop_length = 64, time_deconv = 1.059,time_irff = 110.683
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 512, hop_length = 128, time_deconv = 0.995,time_irff = 55.545
MSE [deconv: 0.00034 / irff: 0.00034 ]@ filter_length = 512, hop_length = 256, time_deconv = 0.962,time_irff = 28.781
MSE [deconv: 0.00214 / irff: 0.00214 ]@ filter_length = 512, hop_length = 512, time_deconv = 0.978,time_irff = 14.052
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 1, time_deconv = 111.975,time_irff = 7264.023
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 2, time_deconv = 54.103,time_irff = 3611.712
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 4, time_deconv = 19.016,time_irff = 1814.419
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 8, time_deconv = 8.667,time_irff = 914.403
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 16, time_deconv = 4.192,time_irff = 454.132
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 32, time_deconv = 2.158,time_irff = 236.426
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 64, time_deconv = 1.646,time_irff = 119.015
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 128, time_deconv = 1.222,time_irff = 58.869
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 1024, hop_length = 256, time_deconv = 1.141,time_irff = 30.062
MSE [deconv: 0.00032 / irff: 0.00032 ]@ filter_length = 1024, hop_length = 512, time_deconv = 1.404,time_irff = 14.324
MSE [deconv: 0.00225 / irff: 0.00225 ]@ filter_length = 1024, hop_length = 1024, time_deconv = 1.478,time_irff = 7.464
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 1, time_deconv = 267.637,time_irff = 7322.560
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 2, time_deconv = 131.021,time_irff = 3714.048
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 4, time_deconv = 53.608,time_irff = 1818.193
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 8, time_deconv = 24.528,time_irff = 915.428
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 16, time_deconv = 11.694,time_irff = 458.785
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 32, time_deconv = 5.827,time_irff = 228.636
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 64, time_deconv = 3.096,time_irff = 114.230
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 128, time_deconv = 2.056,time_irff = 56.802
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 256, time_deconv = 1.492,time_irff = 29.270
MSE [deconv: 0.00023 / irff: 0.00023 ]@ filter_length = 2048, hop_length = 512, time_deconv = 1.380,time_irff = 14.570
MSE [deconv: 0.00034 / irff: 0.00034 ]@ filter_length = 2048, hop_length = 1024, time_deconv = 1.179,time_irff = 7.238
MSE [deconv: 0.00223 / irff: 0.00223 ]@ filter_length = 2048, hop_length = 2048, time_deconv = 1.094,time_irff = 3.745

It's for n=1 run per filter/hop but i hope it helps

**Comment by seungwonpark** [comment]
Wow, thanks so much.
By the way, could you please show us the code that you used for producing that results? It will be really helpful.

**Comment by seungwonpark** [comment]
Checked it at #4. Thank you so much!
